// assets
import { Inter } from 'next/font/google'

// components
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

// styles
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className={styles.main}>
            <div className={styles.description}>
               <p>
                  Get started by editing&nbsp;
                  <code className={styles.code}>pages/index.js</code>
               </p>
            </div>

            <div className={styles.grid}>

               <div className={[styles.center, {backgroundColor: "transparent"}]}>
                  <Image
                     src={"/images/profile_picture.png"}
                     width={200}
                     height={200}
                     alt='profile picture'
                  />
               </div>

               <Link href="games/italiano" className={styles.card}>
                  <h2 className={inter.className}>
                     Italiano <span>-&gt;</span>
                  </h2>
                  <p className={inter.className}>
                     aka my native tongue
                  </p>
               </Link>

               <Link href="games/english" className={styles.card}>
                  <h2 className={inter.className}>
                     English <span>-&gt;</span>
                  </h2>
                  <p className={inter.className}>
                     the language who <strong>stole</strong> my heart
                  </p>
               </Link>

            </div>
         </main>
      </>
   )
}
